name: Docker Image CI

on:
  push:
    branches: [ "edge" ]
  pull_request:
    branches: [ "edge" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Docker/Dockerfile --tag frss:latest
    - name: Deployying
      run: docker run -d -p 80:80 frss:latest
